/*
 * Part of NDLA article-api.
 * Copyright (C) 2020 NDLA
 *
 * See LICENSE
 */

package db.migration

import no.ndla.articleapi.{TestEnvironment, UnitSuite}

class V24__RemoveDomainFromH5PUrlTest extends UnitSuite with TestEnvironment {
  val migration = new V24__RemoveDomainFromH5PUrl

  test(
    "migration should rename data-url to data-path and remove domain url from H5P-urls, and convert data-resource to h5p in LearningResource") {
    /*
    Article data before: The word "external" written in every <p> tag, should not be affected
                         data-resource="external" (the only occurrence of "external" that should be affected)
                         data-url="h5p-url"

    Article data after:  The word "external" still occur in every <p> tag, unaffected
                         data-resource="h5p"
                         data-url - removed
                         data-path="relative h5p-url from data-url"
     */

    val LearningResourceTestBefore =
      """{"tags":[{"tags":["test","test12","testing","erindring","external","h5p"],"language":"nb"}],"notes":[{"note":"Opprettet artikkel.","user":"ZQ3t4C9SiQkUkzXxxlk0IQyM","status":{"other":[],"current":"DRAFT"},"timestamp":"2020-06-03T06:43:13Z"}],"title":[{"title":"image test h5p external","language":"nb"}],"status":{"other":[],"current":"DRAFT"},"content":[{"content":"<section><p>external h5p</p><embed data-resource=\"image\" data-resource_id=\"12669\" data-size=\"fullbredde\" data-align=\"\" data-alt=\"Samiske språkområder i Norge. Illustrasjon. \" data-caption=\"\"><p>h5p</p><br><br><embed data-resource=\"external\" data-url=\"https://h5p-test.ndla.no/resource/89734643-4006-4c65-a5de-34989ba7b2c8\"><p>External</p><br><embed data-resource=\"external\" data-url=\"https://h5p-test.ndla.no/resource/7b67cc63-ebd0-4baf-98ea-00a1ec075d89\"><p>h5p</p><embed data-resource=\"external\" data-url=\"https://h5p-test.ndla.no/resource/dc6679a2-ad66-4783-a655-b09677f40090\"><p>External</p><embed data-resource=\"external\" data-url=\"https://h5p-test.ndla.no/resource/b7b64634-1c57-4a0c-985f-a7278a4c4f0f\"><p>Rexternal huehue</p></section>","language":"nb"}],"created":"2020-06-03T06:43:13Z","updated":"2020-06-08T10:54:51Z","copyright":{"origin":"","license":"CC-BY-SA-4.0","creators":[],"processors":[],"rightsholders":[]},"grepCodes":["KM2257","KE108"],"metaImage":[{"altText":"h5p external","imageId":"28976","language":"nb"}],"published":"2020-06-03T06:43:13Z","updatedBy":"ZQ3t4C9SiQkUkzXxxlk0IQyM","articleType":"standard","editorLabels":[],"introduction":[{"language":"nb","introduction":"external h5p"}],"visualElement":[],"metaDescription":[{"content":"external h5p","language":"nb"}],"requiredLibraries":[],"previousVersionsNotes":[]}"""
    val LearningResourceFFBefore =
      """{"tags":[{"tags":["test","test12","testing","erindring","external","h5p"],"language":"nb"}],"notes":[{"note":"Opprettet artikkel.","user":"ZQ3t4C9SiQkUkzXxxlk0IQyM","status":{"other":[],"current":"DRAFT"},"timestamp":"2020-06-03T06:43:13Z"}],"title":[{"title":"image test h5p external","language":"nb"}],"status":{"other":[],"current":"DRAFT"},"content":[{"content":"<section><p>external h5p</p><embed data-resource=\"image\" data-resource_id=\"12669\" data-size=\"fullbredde\" data-align=\"\" data-alt=\"Samiske språkområder i Norge. Illustrasjon. \" data-caption=\"\"><p>h5p</p><br><br><embed data-resource=\"external\" data-url=\"https://h5p-ff.ndla.no/resource/89734643-4006-4c65-a5de-34989ba7b2c8\"><p>External</p><br><embed data-resource=\"external\" data-url=\"https://h5p-ff.ndla.no/resource/7b67cc63-ebd0-4baf-98ea-00a1ec075d89\"><p>h5p</p><embed data-resource=\"external\" data-url=\"https://h5p-ff.ndla.no/resource/dc6679a2-ad66-4783-a655-b09677f40090\"><p>External</p><embed data-resource=\"external\" data-url=\"https://h5p-ff.ndla.no/resource/b7b64634-1c57-4a0c-985f-a7278a4c4f0f\"><p>Rexternal huehue</p></section>","language":"nb"}],"created":"2020-06-03T06:43:13Z","updated":"2020-06-08T10:54:51Z","copyright":{"origin":"","license":"CC-BY-SA-4.0","creators":[],"processors":[],"rightsholders":[]},"grepCodes":["KM2257","KE108"],"metaImage":[{"altText":"h5p external","imageId":"28976","language":"nb"}],"published":"2020-06-03T06:43:13Z","updatedBy":"ZQ3t4C9SiQkUkzXxxlk0IQyM","articleType":"standard","editorLabels":[],"introduction":[{"language":"nb","introduction":"external h5p"}],"visualElement":[],"metaDescription":[{"content":"external h5p","language":"nb"}],"requiredLibraries":[],"previousVersionsNotes":[]}"""
    val LearningResourceStagingBefore =
      """{"tags":[{"tags":["test","test12","testing","erindring","external","h5p"],"language":"nb"}],"notes":[{"note":"Opprettet artikkel.","user":"ZQ3t4C9SiQkUkzXxxlk0IQyM","status":{"other":[],"current":"DRAFT"},"timestamp":"2020-06-03T06:43:13Z"}],"title":[{"title":"image test h5p external","language":"nb"}],"status":{"other":[],"current":"DRAFT"},"content":[{"content":"<section><p>external h5p</p><embed data-resource=\"image\" data-resource_id=\"12669\" data-size=\"fullbredde\" data-align=\"\" data-alt=\"Samiske språkområder i Norge. Illustrasjon. \" data-caption=\"\"><p>h5p</p><br><br><embed data-resource=\"external\" data-url=\"https://h5p-staging.ndla.no/resource/89734643-4006-4c65-a5de-34989ba7b2c8\"><p>External</p><br><embed data-resource=\"external\" data-url=\"https://h5p-staging.ndla.no/resource/7b67cc63-ebd0-4baf-98ea-00a1ec075d89\"><p>h5p</p><embed data-resource=\"external\" data-url=\"https://h5p-staging.ndla.no/resource/dc6679a2-ad66-4783-a655-b09677f40090\"><p>External</p><embed data-resource=\"external\" data-url=\"https://h5p-staging.ndla.no/resource/b7b64634-1c57-4a0c-985f-a7278a4c4f0f\"><p>Rexternal huehue</p></section>","language":"nb"}],"created":"2020-06-03T06:43:13Z","updated":"2020-06-08T10:54:51Z","copyright":{"origin":"","license":"CC-BY-SA-4.0","creators":[],"processors":[],"rightsholders":[]},"grepCodes":["KM2257","KE108"],"metaImage":[{"altText":"h5p external","imageId":"28976","language":"nb"}],"published":"2020-06-03T06:43:13Z","updatedBy":"ZQ3t4C9SiQkUkzXxxlk0IQyM","articleType":"standard","editorLabels":[],"introduction":[{"language":"nb","introduction":"external h5p"}],"visualElement":[],"metaDescription":[{"content":"external h5p","language":"nb"}],"requiredLibraries":[],"previousVersionsNotes":[]}"""
    val LearningResourceProdBefore =
      """{"tags":[{"tags":["test","test12","testing","erindring","external","h5p"],"language":"nb"}],"notes":[{"note":"Opprettet artikkel.","user":"ZQ3t4C9SiQkUkzXxxlk0IQyM","status":{"other":[],"current":"DRAFT"},"timestamp":"2020-06-03T06:43:13Z"}],"title":[{"title":"image test h5p external","language":"nb"}],"status":{"other":[],"current":"DRAFT"},"content":[{"content":"<section><p>external h5p</p><embed data-resource=\"image\" data-resource_id=\"12669\" data-size=\"fullbredde\" data-align=\"\" data-alt=\"Samiske språkområder i Norge. Illustrasjon. \" data-caption=\"\"><p>h5p</p><br><br><embed data-resource=\"external\" data-url=\"https://h5p.ndla.no/resource/89734643-4006-4c65-a5de-34989ba7b2c8\"><p>External</p><br><embed data-resource=\"external\" data-url=\"https://h5p.ndla.no/resource/7b67cc63-ebd0-4baf-98ea-00a1ec075d89\"><p>h5p</p><embed data-resource=\"external\" data-url=\"https://h5p.ndla.no/resource/dc6679a2-ad66-4783-a655-b09677f40090\"><p>External</p><embed data-resource=\"external\" data-url=\"https://h5p.ndla.no/resource/b7b64634-1c57-4a0c-985f-a7278a4c4f0f\"><p>Rexternal huehue</p></section>","language":"nb"}],"created":"2020-06-03T06:43:13Z","updated":"2020-06-08T10:54:51Z","copyright":{"origin":"","license":"CC-BY-SA-4.0","creators":[],"processors":[],"rightsholders":[]},"grepCodes":["KM2257","KE108"],"metaImage":[{"altText":"h5p external","imageId":"28976","language":"nb"}],"published":"2020-06-03T06:43:13Z","updatedBy":"ZQ3t4C9SiQkUkzXxxlk0IQyM","articleType":"standard","editorLabels":[],"introduction":[{"language":"nb","introduction":"external h5p"}],"visualElement":[],"metaDescription":[{"content":"external h5p","language":"nb"}],"requiredLibraries":[],"previousVersionsNotes":[]}"""

    val LearningResourceAfter =
      """{"tags":[{"tags":["test","test12","testing","erindring","external","h5p"],"language":"nb"}],"notes":[{"note":"Opprettet artikkel.","user":"ZQ3t4C9SiQkUkzXxxlk0IQyM","status":{"other":[],"current":"DRAFT"},"timestamp":"2020-06-03T06:43:13Z"}],"title":[{"title":"image test h5p external","language":"nb"}],"status":{"other":[],"current":"DRAFT"},"content":[{"content":"<section><p>external h5p</p><embed data-resource=\"image\" data-resource_id=\"12669\" data-size=\"fullbredde\" data-align=\"\" data-alt=\"Samiske språkområder i Norge. Illustrasjon. \" data-caption=\"\"><p>h5p</p><br><br><embed data-resource=\"h5p\" data-path=\"/resource/89734643-4006-4c65-a5de-34989ba7b2c8\"><p>External</p><br><embed data-resource=\"h5p\" data-path=\"/resource/7b67cc63-ebd0-4baf-98ea-00a1ec075d89\"><p>h5p</p><embed data-resource=\"h5p\" data-path=\"/resource/dc6679a2-ad66-4783-a655-b09677f40090\"><p>External</p><embed data-resource=\"h5p\" data-path=\"/resource/b7b64634-1c57-4a0c-985f-a7278a4c4f0f\"><p>Rexternal huehue</p></section>","language":"nb"}],"created":"2020-06-03T06:43:13Z","updated":"2020-06-08T10:54:51Z","copyright":{"origin":"","license":"CC-BY-SA-4.0","creators":[],"processors":[],"rightsholders":[]},"grepCodes":["KM2257","KE108"],"metaImage":[{"altText":"h5p external","imageId":"28976","language":"nb"}],"published":"2020-06-03T06:43:13Z","updatedBy":"ZQ3t4C9SiQkUkzXxxlk0IQyM","articleType":"standard","editorLabels":[],"introduction":[{"language":"nb","introduction":"external h5p"}],"visualElement":[],"metaDescription":[{"content":"external h5p","language":"nb"}],"requiredLibraries":[],"previousVersionsNotes":[]}"""

    migration.convertArticleUpdate(LearningResourceTestBefore) should equal(LearningResourceAfter)
    migration.convertArticleUpdate(LearningResourceFFBefore) should equal(LearningResourceAfter)
    migration.convertArticleUpdate(LearningResourceStagingBefore) should equal(LearningResourceAfter)
    migration.convertArticleUpdate(LearningResourceProdBefore) should equal(LearningResourceAfter)
  }

  test(
    "migration rename data-url to data-path and remove domain url from H5P-urls, and convert data-resource to h5p in TopicArticle") {
    /*
    Article data before: The word "external" written in every <p> tag, should not be affected
                         data-resource="external" (the only occurrence of "external" that should be affected)
                         data-url="h5p-url"

    Article data after:  The word "external" still occur in every <p> tag, unaffected
                         data-resource="h5p"
                         data-url - removed
                         data-path="relative h5p-url from data-url"
     */

    val TopicArticleTestBefore =
      """{"tags":[{"tags":["h5p","external"],"language":"nb"}],"notes":[{"note":"Opprettet artikkel.","user":"ZQ3t4C9SiQkUkzXxxlk0IQyM","status":{"other":[],"current":"DRAFT"},"timestamp":"2020-06-03T11:16:41Z"}],"title":[{"title":"H5P test external","language":"nb"}],"status":{"other":[],"current":"DRAFT"},"content":[{"content":"<section><p>external h5p Rexternal</p></section>","language":"nb"}],"created":"2020-06-03T11:16:42Z","updated":"2020-06-08T10:54:20Z","copyright":{"license":"CC-BY-SA-4.0","creators":[],"processors":[],"rightsholders":[]},"grepCodes":[],"metaImage":[{"altText":"external h5p","imageId":"28976","language":"nb"}],"published":"2020-06-03T11:16:42Z","updatedBy":"ZQ3t4C9SiQkUkzXxxlk0IQyM","articleType":"topic-article","editorLabels":[],"introduction":[{"language":"nb","introduction":"external h5p"}],"visualElement":[{"language":"nb","resource":"<embed data-resource=\"external\" data-url=\"https://h5p-test.ndla.no/resource/b9cb9203-5df0-4732-bde0-83347a2a0d53\">"}],"metaDescription":[{"content":"h5p external","language":"nb"}],"requiredLibraries":[],"previousVersionsNotes":[]}"""
    val TopicArticleFFBefore =
      """{"tags":[{"tags":["h5p","external"],"language":"nb"}],"notes":[{"note":"Opprettet artikkel.","user":"ZQ3t4C9SiQkUkzXxxlk0IQyM","status":{"other":[],"current":"DRAFT"},"timestamp":"2020-06-03T11:16:41Z"}],"title":[{"title":"H5P test external","language":"nb"}],"status":{"other":[],"current":"DRAFT"},"content":[{"content":"<section><p>external h5p Rexternal</p></section>","language":"nb"}],"created":"2020-06-03T11:16:42Z","updated":"2020-06-08T10:54:20Z","copyright":{"license":"CC-BY-SA-4.0","creators":[],"processors":[],"rightsholders":[]},"grepCodes":[],"metaImage":[{"altText":"external h5p","imageId":"28976","language":"nb"}],"published":"2020-06-03T11:16:42Z","updatedBy":"ZQ3t4C9SiQkUkzXxxlk0IQyM","articleType":"topic-article","editorLabels":[],"introduction":[{"language":"nb","introduction":"external h5p"}],"visualElement":[{"language":"nb","resource":"<embed data-resource=\"external\" data-url=\"https://h5p-ff.ndla.no/resource/b9cb9203-5df0-4732-bde0-83347a2a0d53\">"}],"metaDescription":[{"content":"h5p external","language":"nb"}],"requiredLibraries":[],"previousVersionsNotes":[]}"""
    val TopicArticleStagingBefore =
      """{"tags":[{"tags":["h5p","external"],"language":"nb"}],"notes":[{"note":"Opprettet artikkel.","user":"ZQ3t4C9SiQkUkzXxxlk0IQyM","status":{"other":[],"current":"DRAFT"},"timestamp":"2020-06-03T11:16:41Z"}],"title":[{"title":"H5P test external","language":"nb"}],"status":{"other":[],"current":"DRAFT"},"content":[{"content":"<section><p>external h5p Rexternal</p></section>","language":"nb"}],"created":"2020-06-03T11:16:42Z","updated":"2020-06-08T10:54:20Z","copyright":{"license":"CC-BY-SA-4.0","creators":[],"processors":[],"rightsholders":[]},"grepCodes":[],"metaImage":[{"altText":"external h5p","imageId":"28976","language":"nb"}],"published":"2020-06-03T11:16:42Z","updatedBy":"ZQ3t4C9SiQkUkzXxxlk0IQyM","articleType":"topic-article","editorLabels":[],"introduction":[{"language":"nb","introduction":"external h5p"}],"visualElement":[{"language":"nb","resource":"<embed data-resource=\"external\" data-url=\"https://h5p-staging.ndla.no/resource/b9cb9203-5df0-4732-bde0-83347a2a0d53\">"}],"metaDescription":[{"content":"h5p external","language":"nb"}],"requiredLibraries":[],"previousVersionsNotes":[]}"""
    val TopicArticleProdBefore =
      """{"tags":[{"tags":["h5p","external"],"language":"nb"}],"notes":[{"note":"Opprettet artikkel.","user":"ZQ3t4C9SiQkUkzXxxlk0IQyM","status":{"other":[],"current":"DRAFT"},"timestamp":"2020-06-03T11:16:41Z"}],"title":[{"title":"H5P test external","language":"nb"}],"status":{"other":[],"current":"DRAFT"},"content":[{"content":"<section><p>external h5p Rexternal</p></section>","language":"nb"}],"created":"2020-06-03T11:16:42Z","updated":"2020-06-08T10:54:20Z","copyright":{"license":"CC-BY-SA-4.0","creators":[],"processors":[],"rightsholders":[]},"grepCodes":[],"metaImage":[{"altText":"external h5p","imageId":"28976","language":"nb"}],"published":"2020-06-03T11:16:42Z","updatedBy":"ZQ3t4C9SiQkUkzXxxlk0IQyM","articleType":"topic-article","editorLabels":[],"introduction":[{"language":"nb","introduction":"external h5p"}],"visualElement":[{"language":"nb","resource":"<embed data-resource=\"external\" data-url=\"https://h5p.ndla.no/resource/b9cb9203-5df0-4732-bde0-83347a2a0d53\">"}],"metaDescription":[{"content":"h5p external","language":"nb"}],"requiredLibraries":[],"previousVersionsNotes":[]}"""

    val TopicArticleAfter =
      """{"tags":[{"tags":["h5p","external"],"language":"nb"}],"notes":[{"note":"Opprettet artikkel.","user":"ZQ3t4C9SiQkUkzXxxlk0IQyM","status":{"other":[],"current":"DRAFT"},"timestamp":"2020-06-03T11:16:41Z"}],"title":[{"title":"H5P test external","language":"nb"}],"status":{"other":[],"current":"DRAFT"},"content":[{"content":"<section><p>external h5p Rexternal</p></section>","language":"nb"}],"created":"2020-06-03T11:16:42Z","updated":"2020-06-08T10:54:20Z","copyright":{"license":"CC-BY-SA-4.0","creators":[],"processors":[],"rightsholders":[]},"grepCodes":[],"metaImage":[{"altText":"external h5p","imageId":"28976","language":"nb"}],"published":"2020-06-03T11:16:42Z","updatedBy":"ZQ3t4C9SiQkUkzXxxlk0IQyM","articleType":"topic-article","editorLabels":[],"introduction":[{"language":"nb","introduction":"external h5p"}],"visualElement":[{"language":"nb","resource":"<embed data-resource=\"h5p\" data-path=\"/resource/b9cb9203-5df0-4732-bde0-83347a2a0d53\">"}],"metaDescription":[{"content":"h5p external","language":"nb"}],"requiredLibraries":[],"previousVersionsNotes":[]}"""

    migration.convertArticleUpdate(TopicArticleTestBefore) should equal(TopicArticleAfter)
    migration.convertArticleUpdate(TopicArticleFFBefore) should equal(TopicArticleAfter)
    migration.convertArticleUpdate(TopicArticleStagingBefore) should equal(TopicArticleAfter)
    migration.convertArticleUpdate(TopicArticleProdBefore) should equal(TopicArticleAfter)
  }

  test("migration does nothing if the document is already converted") {
    val LearningResourceBefore =
      """{"tags":[{"tags":["test","test12","testing","erindring","external","h5p"],"language":"nb"}],"notes":[{"note":"Opprettet artikkel.","user":"ZQ3t4C9SiQkUkzXxxlk0IQyM","status":{"other":[],"current":"DRAFT"},"timestamp":"2020-06-03T06:43:13Z"}],"title":[{"title":"image test h5p external","language":"nb"}],"status":{"other":[],"current":"DRAFT"},"content":[{"content":"<section><p>external h5p</p><embed data-resource=\"image\" data-resource_id=\"12669\" data-size=\"fullbredde\" data-align=\"\" data-alt=\"Samiske språkområder i Norge. Illustrasjon. \" data-caption=\"\"><p>h5p</p><br><br><embed data-resource=\"h5p\" data-path=\"/resource/89734643-4006-4c65-a5de-34989ba7b2c8\"><p>External</p><br><embed data-resource=\"h5p\" data-path=\"/resource/7b67cc63-ebd0-4baf-98ea-00a1ec075d89\"><p>h5p</p><embed data-resource=\"h5p\" data-path=\"/resource/dc6679a2-ad66-4783-a655-b09677f40090\"><p>External</p><embed data-resource=\"h5p\" data-path=\"/resource/b7b64634-1c57-4a0c-985f-a7278a4c4f0f\"><p>Rexternal huehue</p></section>","language":"nb"}],"created":"2020-06-03T06:43:13Z","updated":"2020-06-08T10:54:51Z","copyright":{"origin":"","license":"CC-BY-SA-4.0","creators":[],"processors":[],"rightsholders":[]},"grepCodes":["KM2257","KE108"],"metaImage":[{"altText":"h5p external","imageId":"28976","language":"nb"}],"published":"2020-06-03T06:43:13Z","updatedBy":"ZQ3t4C9SiQkUkzXxxlk0IQyM","articleType":"standard","editorLabels":[],"introduction":[{"language":"nb","introduction":"external h5p"}],"visualElement":[],"metaDescription":[{"content":"external h5p","language":"nb"}],"requiredLibraries":[],"previousVersionsNotes":[]}"""
    val TopicArticleBefore =
      """{"tags":[{"tags":["h5p","external"],"language":"nb"}],"notes":[{"note":"Opprettet artikkel.","user":"ZQ3t4C9SiQkUkzXxxlk0IQyM","status":{"other":[],"current":"DRAFT"},"timestamp":"2020-06-03T11:16:41Z"}],"title":[{"title":"H5P test external","language":"nb"}],"status":{"other":[],"current":"DRAFT"},"content":[{"content":"<section><p>external h5p Rexternal</p></section>","language":"nb"}],"created":"2020-06-03T11:16:42Z","updated":"2020-06-08T10:54:20Z","copyright":{"license":"CC-BY-SA-4.0","creators":[],"processors":[],"rightsholders":[]},"grepCodes":[],"metaImage":[{"altText":"external h5p","imageId":"28976","language":"nb"}],"published":"2020-06-03T11:16:42Z","updatedBy":"ZQ3t4C9SiQkUkzXxxlk0IQyM","articleType":"topic-article","editorLabels":[],"introduction":[{"language":"nb","introduction":"external h5p"}],"visualElement":[{"language":"nb","resource":"<embed data-resource=\"h5p\" data-path=\"/resource/b9cb9203-5df0-4732-bde0-83347a2a0d53\">"}],"metaDescription":[{"content":"h5p external","language":"nb"}],"requiredLibraries":[],"previousVersionsNotes":[]}"""

    migration.convertArticleUpdate(LearningResourceBefore) should equal(LearningResourceBefore)
    migration.convertArticleUpdate(LearningResourceBefore) should equal(LearningResourceBefore)
    migration.convertArticleUpdate(LearningResourceBefore) should equal(LearningResourceBefore)
    migration.convertArticleUpdate(LearningResourceBefore) should equal(LearningResourceBefore)

    migration.convertArticleUpdate(TopicArticleBefore) should equal(TopicArticleBefore)
    migration.convertArticleUpdate(TopicArticleBefore) should equal(TopicArticleBefore)
    migration.convertArticleUpdate(TopicArticleBefore) should equal(TopicArticleBefore)
    migration.convertArticleUpdate(TopicArticleBefore) should equal(TopicArticleBefore)
  }

}
